/*
 * This file is generated by jOOQ.
 */
package ru.ra_tech.garden_manager.database.schema;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.ra_tech.garden_manager.database.schema.tables.Gardens;
import ru.ra_tech.garden_manager.database.schema.tables.Users;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GARDENS_OWNER_INDEX = Internal.createIndex(DSL.name("gardens_owner_index"), Gardens.GARDENS, new OrderField[] { Gardens.GARDENS.OWNER }, false);
    public static final Index USERS_EMAIL_INDEX = Internal.createIndex(DSL.name("users_email_index"), Users.USERS, new OrderField[] { Users.USERS.EMAIL }, true);
    public static final Index USERS_LOGIN_INDEX = Internal.createIndex(DSL.name("users_login_index"), Users.USERS, new OrderField[] { Users.USERS.LOGIN }, true);
}
