/*
 * This file is generated by jOOQ.
 */
package ru.ra_tech.garden_manager.database.schema;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.ra_tech.garden_manager.database.schema.tables.Databasechangelog;
import ru.ra_tech.garden_manager.database.schema.tables.Databasechangeloglock;
import ru.ra_tech.garden_manager.database.schema.tables.Gardens;
import ru.ra_tech.garden_manager.database.schema.tables.GardensParticipants;
import ru.ra_tech.garden_manager.database.schema.tables.UserRoles;
import ru.ra_tech.garden_manager.database.schema.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.gardens</code>.
     */
    public final Gardens GARDENS = Gardens.GARDENS;

    /**
     * The table <code>public.gardens_participants</code>.
     */
    public final GardensParticipants GARDENS_PARTICIPANTS = GardensParticipants.GARDENS_PARTICIPANTS;

    /**
     * The table <code>public.user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Gardens.GARDENS,
            GardensParticipants.GARDENS_PARTICIPANTS,
            UserRoles.USER_ROLES,
            Users.USERS
        );
    }
}
