/*
 * This file is generated by jOOQ.
 */
package ru.ra_tech.garden_manager.database.schema;


import ru.ra_tech.garden_manager.database.schema.tables.Databasechangelog;
import ru.ra_tech.garden_manager.database.schema.tables.Databasechangeloglock;
import ru.ra_tech.garden_manager.database.schema.tables.Gardens;
import ru.ra_tech.garden_manager.database.schema.tables.GardensParticipants;
import ru.ra_tech.garden_manager.database.schema.tables.UserRoles;
import ru.ra_tech.garden_manager.database.schema.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.gardens</code>.
     */
    public static final Gardens GARDENS = Gardens.GARDENS;

    /**
     * The table <code>public.gardens_participants</code>.
     */
    public static final GardensParticipants GARDENS_PARTICIPANTS = GardensParticipants.GARDENS_PARTICIPANTS;

    /**
     * The table <code>public.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
