apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: garden-manager-database-destination
  namespace: {{ namespace }}
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - garden-manager-database