apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: garden-manager-database
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: garden-manager
    app.kubernetes.io/component: core
spec:
  host: {{ db.host }}
  exportTo:
    - "."