apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: garden-manager-database
  namespace: {{ namespace }}
spec:
  hosts:
    - {{ db_host }}
  addresses:
    - {{ db_address }}/32
  endpoints:
    - address: {{ db_address }}
      ports:
        tcp: {{ db_port }}
  ports:
    - number: {{ db_port }}
      name: test-pg
      protocol: TCP
  resolution: STATIC
  location: MESH_EXTERNAL