apiVersion: v1
kind: Service
metadata:
  name: garden-manager-database
  namespace: {{ namespace }}
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: {{ db_port }}
      targetPort: {{ db_port }}
#  endpoints:
#    - address: {{ db_address }}