apiVersion: v1
kind: Service
metadata:
  name: garden-manager-database
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: garden-manager
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: {{ db_port }}
      targetPort: {{ db_port }}