apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: garden-manager-database-rule
  namespace: {{ namespace }}
spec:
  hosts:
    - {{ db_host }}
  tcp:
    - match:
        - port: {{ db_port }}
      timeout: 3s
      route:
        - destination:
            host: {{ db_host }}
            port:
              number: {{ db_port }}
          weight: 100