apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name: core-fluent-bit-config
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/part-of: garden-manager
data:
  fluent-bit.conf: |
    [SERVICE]
      Parsers_File        /fluent-bit/etc/parsers.conf
      log_level           info
    
    [INPUT]
      Name              tail
      Tag               core.*
      Path              /logs/*.log
      Parser            log4j-json
      DB                /fluent-bit/db/tail.db
      Mem_Buf_Limit     10MB
      Refresh_Interval  10
      
    [OUTPUT]
      Name stdout
      Match *
    
    [OUTPUT]
      Name              http
      Match             *
      host              solr.ra-tech.pro
      port              80
      uri               /solr/garden-manager-test/update/json/docs
      format            json
      json_date_key     false
      

  parsers.conf: |
    [PARSER]
      Name          log4j-json
      Format        json
      Time_Key      time
      Time_Format   %Y-%m-%dT%H:%M:%S,%L%z
      Time_Keep     On