apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name: core-fluent-bit-config
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/part-of: garden-manager
data:
  fluent-bit.conf: |
    [SERVICE]
      Parsers_File        /fluentbit/parsers.conf
    
    [INPUT]
      Name              tail
      Tag               garden-manager-core.*
      Path              /logs/*.log
      Parser            log4j
      DB                /fluentbit/tail.db
      Mem_Buf_Limit     10MB
      Refresh_Interval  10
      
    [OUTPUT]
      Name stdout
      Match *

  parsers.conf: |
    [PARSER]
      Name          log4j
      Format        regex
      Regex         ^(?<time>[^ ]* {1}[^ ]*) \[(?<level>[^ ]*)\] \[(?<thread>[^ ]*)\] (?<source>[^ ]*) - (?<message>[^\n]*)?$
      Time_Key      time
      Time_Format   %Y-%m-%d %H:%M:%S.%L
      Time_Keep     On