apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: garden-manager-{{ name }}-service-entry
    app.kubernetes.io/part-of: garden-manager
    app.kubernetes.io/component: core
spec:
  exportTo:
    - "."
  hosts:
    - {{ host }}
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL