apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: solr
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: garden-manager
spec:
  host: {{ solr_host }}
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
          sni: {{ solr_host }}
  exportTo:
    - "."
    - istio-system