apiVersion: v1
kind: Service
metadata:
  name: solr-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443