apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: solr
  namespace: {{ namespace }}
spec:
  host: {{ solr_host }}
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
  exportTo:
    - "."