apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: solr-egw
  namespace: {{ namespace }}
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - name: solr
  exportTo:
    - "."
    - istio-system