apiVersion: v1
kind: Service
metadata:
  name: solr-service
  namespace: {{ namespace }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ solr_port }}
      targetPort: {{ solr_port }}