apiVersion: v1
kind: Service
metadata:
  name: solr-service
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: garden-manager-solr-service
    app.kubernetes.io/part-of: garden-manager
    app.kubernetes.io/component: core
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443