apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: solr-rule
  namespace: {{ namespace }}
spec:
  exportTo:
    - "."
    - istio-system
  hosts:
    - {{ solr_host }}
  gateways:
    - mesh
    - {{ namespace }}/garden-manager-egress-gateway
  http:
    - match:
        - gateways:
          - mesh
          port: 80
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: solr
            port:
              number: 80
    - match:
        - gateways:
            - {{ namespace }}/garden-manager-egress-gateway
          port: 80
      route:
        - destination:
            host: {{ solr_host }}
            port:
              number: 443