apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: solr
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: garden-manager
spec:
  hosts:
    - {{ solr_host }}
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL