apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: garden-manager-egress-gateway
  namespace: {{ namespace }}
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: {{ egress_tcp_port }}
        name: tcp
        protocol: TCP
      hosts:
        - {{ db_host }}