apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: garden-manager-egress-gateway
  namespace: {{ namespace }}
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: {{ db_port }}
        name: test-pg
        protocol: TCP
      hosts:
        - {{ db_host }}
        - garden-manager-database.garden-manager-test.svc.cluster.local