apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: garden-manager-egress-gateway
  namespace: {{ namespace }}
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: {{ egress_tcp_port }}
        name: tcp
        protocol: TCP
      hosts:
        - {{ db_host }}
    - port:
        number: 80
        name:  http
        protocol: HTTP
      hosts:
        - {{ solr_host }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ solr_host }}
      tls:
        mode: PASSTHROUGH