apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: garden-manager-egress-gateway
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: garden-manager
    app.kubernetes.io/component: core
spec:
  selector:
    istio: {{ namespace }}-egressgateway
  servers:
    - port:
        number: {{ egress_tcp_port }}
        name: tcp
        protocol: TCP
      hosts:
        - {{ db.host }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ solr.host }}
        - {{ vault.host }}
        - {{ elasticsearch.host }}
      tls:
        mode: PASSTHROUGH