apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egw-destination
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: garden-manager
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - name: solr
    - name: garden-manager-database
  exportTo:
    - "."
    - istio-system