apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: garden-manager-ingress-gateway
  namespace: {{ namespace }}
spec:
  selector:
    app: garden-manager-core
  servers:
    - port:
        name: http
        number: 18080
        protocol: HTTP
      hosts:
        - "*"