apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: garden-manager-ingress-gateway
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: garden-manager
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - {{ host }}