apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: garden-manager-istio-operator
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: garden-manager
    app.kubernetes.io/component: istio
spec:
  components:
    base:
      enabled: false
    pilot:
      enabled: false
    cni:
      enabled: false
    ztunnel:
      enabled: false
    istiodRemote:
      enabled: false
    egressGateways:
      - name: garden-manager-egressgw
        enabled: true
        namespace: {{ namespace }}
        label:
          istio: garden-manager-egressgateway
          app.kubernetes.io/part-of: garden-manager
          app.kubernetes.io/component: istio-egressgw
        k8s:
          replicaCount: 1
          strategy:
            type: Recreate
          service:
            ports:
              - name: tcp
                port: 9999
                targetPort: 9999
              - name: http
                port: 80
                targetPort: 18080
              - name: https
                port: 443
                targetPort: 10443
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 2
            failureThreshold: 30