apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: garden-manager-network-policy
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: garden-manager
spec:
  podSelector:
    {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ namespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ namespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system