apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: garden-manager-network-policy
  namespace: {{ namespace }}
spec:
  podSelector:
    {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ namespace }}
        - podSelector:
            matchLabels:
              istio: ingress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: {{ namespace }}
    - to:
      - ipBlock:
          cidr: 10.8.0.10/32
      ports:
        - protocol: TCP
          port: {{ db_port }}
    - to:
      - ipBlock:
          cidr: 10.8.0.1/32
      ports:
        - protocol: UDP
          port: 53
