apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: garden-manager-core-rule
  namespace: {{ namespace }}
spec:
  exportTo:
    - "."
  hosts:
    - {{ host }}
  gateways:
    - "{{ namespace }}/garden-manager-ingress-gateway"
    - mesh
  http:
    - name: core-actuator-route
      match:
        - uri:
            prefix: "/actuator"
      route:
        - destination:
            host: garden-manager-core-service.{{ namespace }}.svc.cluster.local
            port:
              number: 8081
    - name: core-api-route
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: garden-manager-core-service.{{ namespace }}.svc.cluster.local
            port:
              number: 8080