apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: garden-manager-core-rule
  namespace: {{ namespace }}
spec:
  hosts:
    - garden-manager.test.cloud.ra-tech.pro
  gateways:
    - {{ namespace }}/garden-manager-ingress-gateway
    - mesh
  http:
    - name: core-route
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: garden-manager-core-service.{{ namespace }}.svc.cluster.local
            port:
              number: 8080