management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metrics
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
        readiness:
          include:
            - readinessState
    prometheus:
      enabled: true
      metrics:
        export:
          enabled: true
  server:
    port: 8081

spring:
  liquibase:
    change-log: db/changelog-root.yaml
  mvc:
    throw-exception-if-no-handler-found: true
    problemdetails:
      enabled: true
  http:
    encoding:
      force: true
  basic:
    enabled: false
  jooq:
    sql-dialect: Postgres