logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:DEBUG}

spring:
  liquibase:
    enabled: false
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}