logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:DEBUG}

spring:
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:false}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

app:
  security:
    refresh-token-exp-timeout-sec: ${REFRESH_TOKEN_EXP_TIMEOUT_SEC}
    access-token-exp-timeout-sec: ${ACCESS_TOKEN_EXP_TIMEOUT_SEC}
