apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garden-manager-egressgw-sds
  namespace: {{ namespace }}
  labels:
    app: garden-manager-egressgw
    app.kubernetes.io/name: garden-manager-egressgw
    app.kubernetes.io/component: istio-egressgw
    app.kubernetes.io/part-of: garden-manager
    istio.io/rev: 1-18-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: garden-manager-egressgw-sds
subjects:
  - kind: ServiceAccount
    name: garden-manager-egressgw-service-account