apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: garden-manager-egressgw-sds
  namespace: {{ namespace }}
  labels:
    app: garden-manager-egressgw
    app.kubernetes.io/name: garden-manager-egressgw
    app.kubernetes.io/component: istio-egressgw
    app.kubernetes.io/part-of: garden-manager
    istio.io/rev: 1-18-2
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
