apiVersion: v1
kind: ServiceAccount
metadata:
  name: garden-manager-egressgw-service-account
  namespaces: {{ namespace }}
  labels:
    app: garden-manager-egressgw
    app.kubernetes.io/name: garden-manager-egressgw
    app.kubernetes.io/component: istio-egressgw
    app.kubernetes.io/part-of: garden-manager
    istio.io/rev: 1-18-2